exclude: 'build'

default_language_version:
    python: python3

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 6306a48f7dae5861702d573c9c247e4e9498e867
    hooks:
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: no-commit-to-branch
        args: ['--branch=main']
    -   id: check-added-large-files
        args: ['--maxkb=5000']
    -   id: end-of-file-fixer
        exclude: '^(.*\.svg)$'
- repo: https://github.com/commitizen-tools/commitizen
  rev: v3.29.0
  hooks:
    - id: commitizen

- repo: https://github.com/pycqa/flake8
  rev: 7.1.1
  hooks:
  - id: flake8
    additional_dependencies:
      - flake8-bugbear == 22.4.25
      - pep8-naming == 0.12.1
      - torchfix
    args: ['--config=.flake8']


- repo: https://github.com/omnilib/ufmt
  rev: v2.7.2
  hooks:
  - id: ufmt
    additional_dependencies:
        - black == 22.12.0
        - usort == 1.0.5

- repo: https://github.com/jsh9/pydoclint
  rev: 0.5.6
  hooks:
    - id: pydoclint
      args: [--config=pyproject.toml]
