# torchtitan Config.toml

[job]
dump_folder = "/nfs/h100/raid/chem/checkpoints"
description = "Llama 3 debug training"
use_for_integration_test = true

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 10
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
enable_color_printing = true
enable_aim = true
save_aim_folder = "aim_debug"

[model]
name = "llama3"
flavor = "debugmodel"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / compiled_rmsnorm / fused_rmsnorm
tokenizer_path = "torchtitan/tokenizers/Llama-3.2-chem-1B-v1/"

[optimizer]
name = "AdamW"
lr = 8e-4

[training]
batch_size = 1
gradient_accumulation_steps = 1
seq_len = 2048
max_norm = 1.0  # grad norm clipping
warmup_steps = 5  # lr scheduler warm up, normally 20% of the train steps
steps = 200
decay_steps_perc = 0.1
num_decays = 4
data_parallel_degree = -1
tensor_parallel_degree = 1
compile = true
dataset = "chemlactica_train"  # supported datasets: c4_test (2K), c4 (177M), chemlactica_train_mini (4K)
data_processing_style="chemlactica_style"
representation_type="SMILES"

[validation]
valid_freq = 2000
enable_valid = true
dataset = "chemlactica_valid"  # supported datasets: chemlactica_valid_mini

# [dataloader]
# special_mode = "yield_tensor"

[experimental]
pipeline_parallel_degree = 1
enable_async_tensor_parallel = false

[checkpoint]
enable_checkpoint = false
# load_folder = "yerevann/Llama-debug/bab005ed36ef4e02a3e62333"
save_folder = "yerevann/Llama-debug"
# load_at_step = 100
create_seed_checkpoint = false
interval_type = "steps"
interval = 100
model_weights_only = false
export_dtype = "float32"
async_mode = "async_with_pinned_mem"  # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'none'  # ['none', 'selective', 'full']
selective_ac_option = '2'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false
