# torchtitan Config.toml

[job]
dump_folder = "./outputs"
description = "Llama 3 debug training"
use_for_integration_test = true

[profiling]
enable_profiling = true
save_traces_folder = "profile_trace"
profile_freq = 10
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
enable_color_printing = true
# enable_aim = true
# save_aim_folder = "aim"
#aim_hash = "1d56ec7bed87438684a8da6b"
#aim_experiment_name = "hello"

[model]
name = "llama3"
flavor = "debugmodel"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / compiled_rmsnorm / fused_rmsnorm
# test tokenizer.model, for debug purpose only
tokenizer_path = "./torchtitan/tokenizers/chemlactica-125m"
init_weights = true

[optimizer]
name = "AdamW"
lr = 8e-4

[training]
batch_size = 1
gradient_accumulation_steps = 1
seq_len = 2048
warmup_steps = 2  # lr scheduler warm up, normally 20% of the train steps
max_norm = 1.0  # grad norm clipping
steps = 30
data_parallel_degree = -1
tensor_parallel_degree = 1
compile = false
dataset = "c4_test"  # supported datasets: c4_test (2K), c4 (177M)

[dataset]
use_experimental_dataloader = false
data_logical_shards = 768
bos_token = 128000
eos_token = 128001
# dataset_path = "/fsx/datasets/"
# datasets = "CommonCrawl,C4,Github,Wikipedia,Books,ArXiv,StackExchange"
# dataset_weights = "67,15,4.5,4.5,4.5,2.5,2"
dataset_path = "./torchtitan/datasets/experimental/llama3"
datasets = "c4_mini"
dataset_weights = "1"
num_data_workers = 1
# dataset = "chemlactica_train_mini"  # supported datasets: c4_test (2K), c4 (177M), chemlactica_train_mini (4K)
# data_process_style="chemlactica_style"

[experimental]
pipeline_parallel_degree = 1
enable_async_tensor_parallel = false

[checkpoint]
enable_checkpoint = true
save_folder = "checkpoint"
load_folder = "checkpoint"
create_seed_checkpoint = false
interval_type = "steps"
interval = 5
model_weights_only = false
export_dtype = "float32"
async_mode = "async_with_pinned_mem"  # ["disabled", "async", "async_with_pinned_mem"]

[activation_checkpoint]
mode = 'selective'  # ['none', 'selective', 'full']
selective_ac_option = '2'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false
