# torchtitan Config.toml

[job]
dump_folder = "${oc.env:DUMP_DIR}"
description = "Llama 3.2 training"
use_for_integration_test = false

[profiling]
enable_profiling = false
save_traces_folder = "profile_trace"
profile_freq = 10
enable_memory_snapshot = false
save_memory_snapshot_folder = "memory_snapshot"

[metrics]
log_freq = 1
enable_color_printing = true
enable_aim = false
save_aim_folder = "aim"

[model]
name = "llama3"
flavor = "3B"
norm_type = "rmsnorm"  # layernorm / np_layernorm / rmsnorm / compiled_rmsnorm / fused_rmsnorm
# tokenizer_path = "torchtitan/tokenizers/Llama-3.2-chem-1B-v1"
tokenizer_path = "meta-llama/Llama-3.2-1B"

[optimizer]
name = "AdamW"
lr = 1.0e-4

[training]
batch_size = 1
gradient_accumulation_steps = 3
seq_len = 2048
warmup_steps = 500  # lr scheduler warm up, normally 20% of the train steps
max_norm = 1.0  # grad norm clipping
steps = 10
data_parallel_degree = -1
tensor_parallel_degree = 1
compile = false
# dataset = "c4"  # supported datasets: c4_test (2K), c4 (177M)
# dataset = "chemlactica_train_mini"  # supported datasets: c4_test (2K), c4 (177M), chemlactica_train_mini (4K)
dataset = "chemlactica_train"
data_processing_style="chemlactica_style"

[experimental]
pipeline_parallel_degree = 1
enable_async_tensor_parallel = false

[checkpoint]
enable_checkpoint = true
# load_folder = "meta-llama/Llama-3.2-1B"
# save_folder = "meta-llama/Llama-3.2-1B"
# load_folder = "yerevann/Llama-3.2-3B/2997328af3694a2794c33a49"
load_at_step = 0
save_folder = "hf-4.52.4/yerevann/Llama-3-3.2B/2997328af3694a2794c33a49"
interval_type = "steps"
interval = 1000
model_weights_only = false
export_dtype = "float32"
async_mode = "async_with_pinned_mem"  # ["disabled", "async", "async_with_pinned_mem"]

[model_download_export]
# to_titan = true
# weights_source = "huggingface"
to_hf = true

[activation_checkpoint]
mode = 'none'  # ['none', 'selective', 'full']
selective_ac_option = '2'  # 'int' = ac every positive int layer or 'op', ac based on ops policy

[float8]
enable_float8_linear = false
